### ISSUE TITLE
XP when purchasing Empower Self

### ISSUE THREAD

**Issue by akaan** [zzorba/ArkhamCards#102]
Hi !

When purchasing all 3 copies of Empower Self, the app counts 6 XP instead of 2. It does it fine for other Myriad cards but these ones are specific because they don't share the same subtitle.

As always thanks for your work !

**Comment by zzorba** [comment]
Thank you for the report -- turns out I was keying off the 'real_text' instead of the 'real_name' 🤦 

Fix will be in next release

**Comment by zzorba** [comment]
Fix for this is out on IOS + Beta Android, production android soon.
