### ISSUE TITLE
Crash when trying to filter on Allowed cards view

### ISSUE THREAD

**Issue by akaan** [zzorba/ArkhamCards#13]
Hi ! Nice work on the latest version.

The application (iOS) crashes when trying to bring the filter menu on the Allowed cards view.
Steps to reproduce :

- from the player cards section, go to an investigator card (say Finn)
- then click on "Deckbuilding Cards" to go to the list of cards allowed for this investigator
- then click the filter icon (example: I want to see allowed allies)
- application crashes

**Comment by zzorba** [comment]
Thanks for the bug report, sorry about this.

I pushed a fix for this up to Apple last night (1.5.1), which should hopefully clear App Store review today/tomorrow.
