### ISSUE TITLE
Deck titles missing when quick searching

### ISSUE THREAD

**Issue by akaan** [zzorba/ArkhamCards#130]
In the Decks section, when I type some text in the search field, filtering do happens but the decks have no titles.

![image](https://user-images.githubusercontent.com/3703235/104810246-8a116f80-57f3-11eb-9989-b9e166060f7c.jpeg)

Titles come back as soon as I scroll the list.

**Comment by zzorba** [comment]
That’s a weird bug. Thank you for reporting, will see what I can do about it. Have a few ideas.

**Comment by zzorba** [comment]
Tracked it down, will be fixed in next release.

**Comment by zzorba** [comment]
Fix should be out on both platforms.
