### ISSUE TITLE
Feature Request - Ignore punctuation symbols when sorting cards

### ISSUE THREAD

**Issue by tjanu** [zzorba/ArkhamCards#139]
I'd love it if there were an option in the settings to ignore punctuation symbols when sorting cards (including ", ', etc. basically UTF-8 general punctuation and other punctuation character classes), since in my opinion,  a card shouldn't be sorted at the beginning or end of a block just because it's name is in quotation marks.

Already read up a bit on this, and it doesn't seem to be trivial to get SQLite, especially on Android, to do that. Essentially, a "normalized_name" column (filled on import) would be needed for that, with the option setting deciding which column to base the sort on. No idea if there's an easier way on iOS, but this approach would work universally.

I realize this might be too much work, and, given some pointers on which files I'd need to touch to adjust the DB schema and import and a short explanation of how settings are handled in ReactNative/this app, I might give this a shot myself - I'm just not exactly well versed in ReactNative (C++/Qt developer...).
Just wanted to formulate it as an issue to gauge whether there might be interest by others, and to collect feedback on how to do that.

**Comment by tjanu** [comment]
To refresh this a bit, I just recently found that there is an option to ignore punctuation, but at least in the German version not all punctuation is ignored by this (specifically, the quotation marks used on the german cards are not `"` but `„”`), which leads to all cards with "quote titles" to be sorted at the very end instead of where the first actual letter would put them.

**Comment by zzorba** [comment]
Could you list the punctuation used (including smart quotes (curved) and normal if they both exist). I can add them to the exclusion list.

**Comment by tjanu** [comment]
Sorry it took so long:
```
…
„
”
‚
‛
"
```

**Comment by tjanu** [comment]
Works after recent update, done from my point of view
