### ISSUE TITLE
Investigator with no associated deck cannot update XP

### ISSUE THREAD

**Issue by sirrus233** [zzorba/ArkhamCards#167]
I am in a campaign with two investigators. One investigator has a deck which is tracked in the app, but the other does not.

I cannot update the spent xp value for the investigator with no deck. When I press "edit", I can adjust the value up or down, but this does not actually appear to modify anything after I press "done".

App version: Android, 2.11.16 (as reported on Google Play)

**Comment by zzorba** [comment]
Hi @sirrus233, could you double check that this is still broken in the app store release? I thought my fix went out yesterday (which is version 2.11.16, but it was released maybe 3 hrs before you reported this issue).  It's possible I overlooked something in the implementation though, or maybe just cut the wrong build for Android.

Also, just to confirm, is this a 'guided' campaign (that includes the setup/resolutions for each scenario), or a manual one?

**Comment by sirrus233** [comment]
I checked that I have the latest that's available on the Google Play store - and the installed version on my phone is 2.11.16

As far as I can tell, the most recent version available on the app store was released April 26? Have you released anything since then?

This is a guided campaign, specifically "Forgotten Age".

**Comment by zzorba** [comment]
Yeah, its definitely version 2.11.16, but I *thought* it was released on April 28th.  Regardless, seems like I must have messed up the build in some way, so I'll cut a new release to be sure.

If you're able to, could you go to Settings -> Diagnostics -> Export diagnostic data and email me the contents to arkhamcards@gmail.com.  Just one to confirm an assumption or two.

**Comment by sirrus233** [comment]
Sent!

**Comment by sirrus233** [comment]
Worth pointing out - I have not updated my app since noticing the bug and filing this issue, but I was just able to update the XP. Not sure what that's about..

**Comment by zzorba** [comment]
That's good to know.  The way that Google Play chooses to upgrade apps is a bit mysterious at times -- Sometimes you can see an update in the app store but it won't actually download it yet -- I'm not a big enough android user to understand the full reasons for this.

I just promoted version 2.12.0 to be sure this fix is out widely now.
