### ISSUE TITLE
Text output problem (Korean)

### ISSUE THREAD

**Issue by derornos** [zzorba/ArkhamCards#198]
About half of the height of the Korean text appears cropped. (default font size)

- rule's title
- Text: Review records
- Text: Review and draw tokens
- ...

![text_problem](https://user-images.githubusercontent.com/15874357/122164282-81f85180-ceb1-11eb-8f10-b858b7c5fe55.jpg)

※ android, arkhamcards beta ver 21.06.13.

**Comment by zzorba** [comment]
Pushed a fix for this, should go out shortly.

**Comment by zzorba** [comment]
Fix for this should be out, though there are still some more issues I plan to address on the Beta branch with respect to android fonts.
