### ISSUE TITLE
getCurrentState is not a function

### ISSUE THREAD

**Issue by suxur** [zzorba/ArkhamCards#20]
I'm trying to get this running locally and encountered the following issue. 

`_nativeInterface.default.getCurrentState is not a function`

I feel like I might be missing a step in setting it up...

Steps taken to get to this point.

1. Cloned repo
2. Ran `npm install`
3. `cd ios` and ran `pod install`
4. Created a local instance of ArkahamDB that's running on `http://127.0.0.1:8000`
5. Copied `.env.local` to `.env`, created OAuth key on ArkhamDB and added the keys
6. Opened `ArkhamCards.xcworkspace`
7. In Xcode pressed `Build & Run`

**Comment by zzorba** [comment]
Hmm, those instructions all sound correct. Let me take a look tomorrow, see if there’s anything else that I do here.

Often I build with the CLI tool, but the workspace file should work as well.

**Comment by suxur** [comment]
I just tried to run with the command `react-native run-ios` and I got the same error.

**Comment by suxur** [comment]
Narrowed down the issue.

In `../node_modules/react-native-cached-image/CachedImage.js` line 22 it's loading

`import NetInfo from "@react-native-community/netinfo";`

NetInfo is throwing that error. Commenting that line out fixed the issue and the app is now running.

**Comment by zzorba** [comment]
Are you running with the Legacy Build System in XCode?   Under File -> Workspace Settings.
![image](https://user-images.githubusercontent.com/1091291/64081287-cca0dd80-cccc-11e9-9bbd-499df6ba5879.png)

**Comment by suxur** [comment]
I’m not sure. I’ll check when I get back to my computer. I did update NetInfo from version 2 to 4 and it seems to be working now!

**Comment by zzorba** [comment]
Awesome will see if I can merge that upgrade, I’m worried that it might
have an androidX update (and I’m not quite ready to move to RN60 yet).

**Comment by suxur** [comment]
Yes, Xcode is running with Legacy Build System. I downgraded NetInfo to `3.2.1` and it's still working! From what I can tell the AndroidX update happens in version 4.

**Comment by zzorba** [comment]
I’ll push a fix so that master is workable.

Let me know if you have any other questions about the code base, sorry it’s not better documented. You can find me at arkhamcards at gmail
