### ISSUE TITLE
bug(?): zaw campaign story assets

### ISSUE THREAD

**Issue by derornos** [zzorba/ArkhamCards#213]
![zaw_ko](https://user-images.githubusercontent.com/15874357/124069189-b86bca00-da76-11eb-908c-bad5db30b5e5.jpg)

(I checked it in the beta version dated June 29)

Why am I not seeing the Korean version of the story assets of the zaw campaign?

I only see the English version of that cards.

ko version of zaw story assets: [link](https://github.com/zzorba/arkham-cards-data/blob/master/i18n/ko/cards/zaw.json)

**Comment by zzorba** [comment]
I missed the fact that these had been updated, and had to do a manual import to my server.

If you go and resync the cards (Might have to go to settings -> Diagnostics -> Clear Card cache), the translations should show up now.

**Comment by derornos** [comment]
okay, i got it. thx!
