### ISSUE TITLE
Feature Request – Utilize Keyboard For Drawing Chaos Tokens

### ISSUE THREAD

**Issue by buffaloseven** [zzorba/ArkhamCards#237]
Recently I moved to an iPad, and I've been using ArkhamCards in a keyboard case far more frequently. It would be great if I could just hit the spacebar to draw a single token, number keys 1-9 to draw X tokens, and a subsequent space bar to return all tokens.

**Comment by zzorba** [comment]
Interesting -- I've never interacted with the Keyboard on an iPad, but it seems like it's very doable.  

I'll explore what that takes.

**Comment by zzorba** [comment]
Okay, I got this working locally and will include it in the next release.

**Comment by G-Rowell** [comment]
@zzorba 

I've tested this locally & on the production / live app.

They both seem to work, so this issue could be closed maybe?
