### ISSUE TITLE
eoe voting issue

### ISSUE THREAD

**Issue by elkeinkrad** [zzorba/ArkhamCards#287]
I played eoe campaign, the city of elder thing scenario.

During campaign, the partner states are following:
 * Kensler (death by crash), Eliyah (death from forbidden peaks)
 * Takata (MIA by the disappearance but rescued)
![image](https://user-images.githubusercontent.com/41584047/145680978-973b3b39-f6f1-46d0-9a20-372f075192f8.png)

Therefore, the voting result should be group three. 2 for group one (Elsworth, Sinha), 2 for group two (Danforth, Takada), and 3 for group three (Dyer, Claypool, Cookie). However, group two is automatically selected from the app.
![image](https://user-images.githubusercontent.com/41584047/145680981-31afea1b-a063-430e-a0c8-23e73c510498.png)

**Comment by zzorba** [comment]
Thank you for reporting this, I accidentally swapped Eliyah and Dyer's votes.  Will fix in next release.

**Comment by elkeinkrad** [comment]
Thanks for your reply and fixing this :)
