### ISSUE TITLE
Error in spanish translations

### ISSUE THREAD

**Issue by iserrano75** [zzorba/ArkhamCards#30]
Hi,

The correct spanish translation for "The circle undone" is "El círculo roto" and not "El circulo desecho" as it shows in the last version.

**Comment by zzorba** [comment]
Thanks for report, will push out a fix in the coming weeks.

**Comment by zzorba** [comment]
I believe this has been fixed and deployed now (sorry for delay, got stuck behind a lot of stuff).  

If you're interested/available to help proof other parts of the spanish translation, let me know and I can provide some guidelines on how to help out there.

**Comment by iserrano75** [comment]
Hi, thanks for the fix. I'm available to help you with the spanish
translation.

**Comment by zzorba** [comment]
Thanks for the interest!

I added some info on how to handle translations to the main README here -- https://github.com/zzorba/ArkhamCards#translations. The best tool to use here is the free version of PoEdit (or any program that is able to open `gettext` translation files). 

If you'd like to open a pull request with updated translations that would be great. You can also transfer the file to me and I can take care of merging and deploying it.

**Comment by midraed** [comment]
With the last PR, I think you can close this issue.
