### ISSUE TITLE
[bug] "Sort ignores punctuation" option is inverted

### ISSUE THREAD

**Issue by gjalsem** [zzorba/ArkhamCards#313]
See title. I have to turn the option off to enable ignoring punctuation. Happening in the latest version from Google Play.

Looks like this bug was introduced in this recent commit: https://github.com/zzorba/ArkhamCards/commit/ef322ebbc589c89c4c0492b4d30245b70dae2024

`sort_quotes` corresponds to `sortRespectQuotes` in one place, and to `sortIgnoreQuotes` in another place.

**Comment by gjalsem** [comment]
With the latest update from the Play store, this problem is fixed for me.

Not sure what happened; I don't see a commit that would fix this. Maybe I was mistaken about what caused this in the first place.

Anyway, all good now. Thanks for this great app!

**Comment by zzorba** [comment]
Oh yes, I fixed this after you reported. Sorry for not responding sooner, have been heads down researching a weird android crash.

thanks for the report!
