### ISSUE TITLE
Feature request: Show bonded cards in Deck Checklist

### ISSUE THREAD

**Issue by javnik36** [zzorba/ArkhamCards#319]
Hi!

Consider adding bonded cards to Deck Checklist (as far as I can see, bonded cards are not showing up in it currently) - it would be a great addition to this feature.

Thanks again for your work on this app - really like it!

**Comment by zzorba** [comment]
Good suggestion, I’ll take a look at this

**Comment by javnik36** [comment]
Appears that it was added in 1a8f1a43bcbd51dc1a9447a62cb6c0cf4618edbb and is showing up in Android v. 2.15.25. Closing the issue then.

Thanks again for adding this :)
