### ISSUE TITLE
[Question] Missing polish content included in arkham-cards-data repo

### ISSUE THREAD

**Issue by javnik36** [zzorba/ArkhamCards#323]
Hi,
just a question, as I am curious about the process itself. As new app's version is out on Google Play I don't see any polish translation content from arkham-cards-data repo in the app. 
It appears that files are imported from the other repo into [ArkhamCards](https://github.com/zzorba/ArkhamCards)/[assets](https://github.com/zzorba/ArkhamCards/tree/master/assets)/[generated](https://github.com/zzorba/ArkhamCards/tree/master/assets/generated)) folder and the pl files are not there. So here my question - is it something wrong with them, or generating this files requires some additional work to be done? Or maybe certain translation needs to more progressed as it is right now? 

Appreciate all the work you're doing!

**Comment by zzorba** [comment]
Sure enough, I hadn't enabled it in the repository.  Will cut a new release today to address this, will take a few days to get out though.
