### ISSUE TITLE
[Bug] Issues with supplies in 'Interlude V: The Darkness' (FTA)

### ISSUE THREAD

**Issue by derornos** [zzorba/ArkhamCards#331]
![bug_1](https://user-images.githubusercontent.com/15874357/159211046-26cb751a-9960-4558-a96f-69cfc1b448d2.jpg)
![bug_2](https://user-images.githubusercontent.com/15874357/159211057-2ab1b20c-15ab-4b36-ba1c-b3e87d620946.jpg)

"Cross off all provisions and medicine the investigators have remaining in their supplies."
It seems that that entry doesn't actually apply.

**Comment by zzorba** [comment]
Thanks for letting me know about this.  It's mostly a thematic campaign log entry (won't impact future decisions any), but I'll get it fixed in the next release.
