### ISSUE TITLE
Level filtering button

### ISSUE THREAD

**Issue by derornos** [zzorba/ArkhamCards#336]
When editing a deck,
I want the 0 level filtering button to be disabled when I press the 1-5 level filtering button to activate it, and the 1-5 level filtering button to be disabled when I press the 0 level filtering button to activate it.

If i wants to check all the cards again, i will have to press the activated level filtering button to make it inactive.

Currently, all of the level filtering buttons activated has the same effect as only all level filtering buttons are deactivated.

**Comment by zzorba** [comment]
That makes a lot of sense, treat it like a radio button but let’s you toggle it off as well.


Will do this right away

**Comment by zzorba** [comment]
https://github.com/zzorba/ArkhamCards/commit/0f3d8b1318942f35734efb07057c0305990741f1
