### ISSUE TITLE
[Bug?] odds calulator

### ISSUE THREAD

**Issue by derornos** [zzorba/ArkhamCards#363]
![SmartSelect_20220522-022438_ArkhamCards](https://user-images.githubusercontent.com/15874357/169662665-7efee29c-a2f1-4b60-ab91-ffc65e4c0c3c.jpg)

![SmartSelect_20220522-022311_ArkhamCards](https://user-images.githubusercontent.com/15874357/169662671-bf88e3d6-0b76-45eb-9902-59bf035ad1d6.jpg)

how to fix it?

**Comment by zzorba** [comment]
I reimported the cards, I think they might have been missing the back_text before?

Could you try reloading cards from arkhamdb and see if that fixes it?

**Comment by derornos** [comment]
Finally got it fixed. thank you.
