### ISSUE TITLE
Feature Request: Can the app support beta versions of cards?

### ISSUE THREAD

**Issue by derornos** [zzorba/ArkhamCards#372]
Can the app support beta versions of cards?

Arkham Pride Council 2022
Council in Exile 2020
...

thanks.

**Comment by zzorba** [comment]
I can, but you won’t be able to add them to ArkhamDB decks. 

If that’s okay, could you link me to the images?

**Comment by derornos** [comment]
I understand that it will work with the aw, dm and bh cards. Looks good!
I'll share links to the image.

.

Council-in-Exile

[en: burn_after_reading lv1](https://images-cdn.fantasyflightgames.com/filer_public/47/fb/47fb99a0-e5d7-42b9-9610-042ba30d4c03/burn_after_reading.pdf), [en: guard_dog lv2, flashlight lv2](https://images-cdn.fantasyflightgames.com/filer_public/d5/46/d546dc41-810f-4c62-b7b8-18a8d7bd2453/an_council_2020_with_bleed.pdf)

[ko: burn_after_reading lv1, guard_dog lv2, flashlight lv2](https://drive.google.com/drive/folders/1opL2yACg4Yo8y1EKdIhvXfJ_6tRuUM1M)

.

The Pride of Arkham Council

[en: dragon_pole lv3, alice_luxley lv2](https://images-cdn.fantasyflightgames.com/filer_public/e4/b9/e4b926c0-ca54-4e07-933c-255be858cad0/an_council_2022_cards_with_bleed.pdf)

[ko: dragon_pole lv3, alice_luxley lv2](https://downapi.cafe.naver.com/v1.0/cafes/article/file/03e1e5fa-f34d-11ec-a7b0-0050568d055f/download)

**Comment by derornos** [comment]
thanks!
