### ISSUE TITLE
[Bug?] conflict in the translations for the two items.

### ISSUE THREAD

**Issue by derornos** [zzorba/ArkhamCards#374]
There is a conflict in the translations for the two items below.

'src\components\filter\CardAssetFilterView\index.tsx: line 49'
Supplies = 소모품
≒ consumables, expendables, consumable[expendable] supplies[goods]

'src\components\campaign\constants.ts: line 479'
Supplies = 탐험 물자
≒ materials for exploration

It seems that something like c('uses') should be added to the former item.

**Comment by zzorba** [comment]
I'll add a context to the one from filters.

**Comment by zzorba** [comment]
Updated, and changed the KO translations appropriately to match your suggestions

**Comment by derornos** [comment]
thanks!
