### ISSUE TITLE
[Bug?] Some lines of text are cut off.

### ISSUE THREAD

**Issue by derornos** [zzorba/ArkhamCards#376]
When taking special chaos tokens(like skull, cultist, ...) from the digital chaos bag in some scenarios, if there are many lines of text on the reference card, some of them will be truncated.

![hotel](https://user-images.githubusercontent.com/15874357/176949540-4c30f600-1cdf-4b86-b221-72372ea822e6.jpg)

**Comment by derornos** [comment]
I checked the app, and the same problem is still happening.
(22.10.11. ver. 3.4.0)

ex.
_[skull]: -X. X is the number of Guest enemies in play._ (truncated.)
[cultist]: -1. If there is an Innocent enemy in the victory display, reveal another chaos token.
[tablet]: -3. You may place one of your clues on your location to treat this as a -1 instead.
[elder_thing]: -3. If you fail and there is an Innocent enemy in the victory display, take 1 horror.

**Comment by derornos** [comment]
@zzorba 
I checked the app, and the same problem is still happening.
(22.10.11. ver. 3.4.0)

ex.
_[skull]: -X. X is the number of Guest enemies in play._ (truncated.)
[cultist]: -1. If there is an Innocent enemy in the victory display, reveal another chaos token.
[tablet]: -3. You may place one of your clues on your location to treat this as a -1 instead.
[elder_thing]: -3. If you fail and there is an Innocent enemy in the victory display, take 1 horror.

**Comment by zzorba** [comment]
I finally tracked this down (I believe).

It was inadvertently matching to a 'link definition' markdown rule that was built into the parser. I took it out and it seemed to come back.

will be in next release

**Comment by derornos** [comment]
yeah~ XD

thanks!
