### ISSUE TITLE
Wrong ptc interlude 1 title.

### ISSUE THREAD

**Issue by derornos** [zzorba/ArkhamCards#377]
'reality's shadow' is correct, not 'skeptic's reward'.

![ptc](https://user-images.githubusercontent.com/15874357/177005901-3a0b12e0-d376-4317-aae9-8aa6951c701f.png)

**Comment by zzorba** [comment]
Good catch!  I was basing my language off Maxine's comment, will update it.

**Comment by derornos** [comment]
good!
