### ISSUE TITLE
[Question] how to choose resolution 2 (tdeb: tsh)

### ISSUE THREAD

**Issue by derornos** [zzorba/ArkhamCards#392]
![20220815_222255087](https://user-images.githubusercontent.com/15874357/184643617-2dc02e88-ab09-41d9-aaa5-2fc9de6149d7.jpg)

It seems that the hidden property of resolution2 is set to true.

**Comment by derornos** [comment]
Please check side b of the following card.

https://ko.arkhamdb.com/card/06171

**Comment by zzorba** [comment]
Yep, that's a mistake I made when trying to make some of these non selectable.

For now you can select No resolution and just choose eliminated (no trauma), it will lead to the same place.

Will fix

**Comment by derornos** [comment]
thanks : )

**Comment by derornos** [comment]
@zzorba 

The same issue occurred in ptc 'echoes of the past' scenario(resolution 4).
[https://ko.arkhamdb.com/card/03123](https://ko.arkhamdb.com/card/03123)

Could you please check the hidden option?

**Comment by zzorba** [comment]
Sure enough!  Someone on the discord did the legwork on this, and it looks like there were a few mistakes made.

Will correct in next release.

**Comment by derornos** [comment]
thanks XD
