### ISSUE TITLE
XP for Myriad cards

### ISSUE THREAD

**Issue by akaan** [zzorba/ArkhamCards#40]
According to the rules, when purchasing a Myriad card you can include all 3 copies but paying only the XP cost once.

@zzorba I'm pretty sure you're aware of that one but I file in the issue so you can have the joy pf closing it 😉

**Comment by zzorba** [comment]
Thanks for the report, I see what happened. I made it work for upgrades but not when building standalone decks.

Will fix, thanks for bug report.

**Comment by zzorba** [comment]
Will be fixed in version 2.0.4 which I'm packing up now.
