### ISSUE TITLE
[Feature Request] add a step for physical and/or mental traumas

### ISSUE THREAD

**Issue by derornos** [zzorba/ArkhamCards#402]
Hi!

When the app adds draw weakness step to start of campaigns, I wish there was also a trauma adjustment step.
( Arcane Research, In the Thick of it, ... )

This is because trauma cannot be adjusted until the campaign setup phase is complete.
(this is often the cause of forgetting to add trauma before the first scenario.)

Thanks : )

**Comment by zzorba** [comment]
That's a good idea.  I think I'll throw it into the save decks step (which means you have to draw weaknesses or at least enter them into the app for it to let you enter trauma)?  That seems okay righjt?

**Comment by derornos** [comment]
oh. very nice idea : )

trauma, extra xp, ...
I think it's a great way to get all of this done in one go!
