### ISSUE TITLE
An Agenda cards appears in player cards

### ISSUE THREAD

**Issue by akaan** [zzorba/ArkhamCards#41]
![5F0E7BA3-C347-4E11-BD58-795C17B7C533](https://user-images.githubusercontent.com/3703235/73738479-d4b1ed00-4744-11ea-8ae0-6f8bdb57c17c.png)

This agenda from Before the Black Throne is listed in player cards lists (whatever the filter applied.
I looked into the data for this card on arkhamdb-json-data but it seems correct to me.

**Comment by zzorba** [comment]
Thanks for report, I saw this the other day but couldn’t figure it out.

Will take another look.

**Comment by zzorba** [comment]
Hi @akaan I think I know what happened here -- at one point the card was wrong but it eventually got updated.

If you go to the app under Settings > Diagnostics and select 'Clear Cache', it will force a full refresh of the player cards. This fixed it for me on my local device.

Next time I have to do a schema change this will happen automatically.

**Comment by akaan** [comment]
It worked, thanks !
