### ISSUE TITLE
[Bug] Customizable card issues

### ISSUE THREAD

**Issue by derornos** [zzorba/ArkhamCards#414]
![image](https://user-images.githubusercontent.com/15874357/190935627-f5b6d758-1ee2-400b-9bbe-d74aca1e75e9.png)

![image](https://user-images.githubusercontent.com/15874357/190935678-2b401ec1-fbf5-4251-a2b4-8449ca6467e5.png)

Error msg: "You cannot have more than 15 level 0-1 Seeker and/or Mystic cards"

It seems to be the same issue as the '[Rite of Equilibrium](https://arkhamdb.com/card/07308)' card.

**Comment by derornos** [comment]
![image](https://user-images.githubusercontent.com/15874357/190937331-365faa26-bf8d-4516-aa70-a1e6693d58c8.png)

![image](https://user-images.githubusercontent.com/15874357/190937353-7a2528ac-380d-443e-aa07-50c35f31c05b.png)

Isn't that 2 XP each on 2 cards?

**Comment by derornos** [comment]
![image](https://user-images.githubusercontent.com/15874357/190937851-fbb9dbca-98a6-48f3-8542-7745e197af30.png)

It seems that these cases should also be considered.

**Comment by zzorba** [comment]
Yeah, I think most of those should be working, in terms of showing up and only becoming valid when it’s checked off.

carolyn is

**Comment by zzorba** [comment]
Okay, have these two working locally.

**Comment by derornos** [comment]
thanks

**Comment by zzorba** [comment]
Yep fixed this today, will submit fix and make sure it’s in the Android release

**Comment by zzorba** [comment]
Thanks again for the report.

These should all be deployed now, please open a new issue if you encounter further problems with customizable.
