### ISSUE TITLE
[Bug] Its loading forever when searching cards using Non-ASCII characters

### ISSUE THREAD

**Issue by derornos** [zzorba/ArkhamCards#418]
https://user-images.githubusercontent.com/15874357/193979994-476a6c8e-da44-4241-9a49-f0abb219b15c.mp4

I tried to search cards using korean (non-ascii).

So, its loading forever.

My guess is that the app doesn't know when to start searching.

However, when I search in English or move the cursor to another place after searching for non-ascii characters, the app performs the search.

**Comment by zzorba** [comment]
Thanks for this report, found a bug here (not related to ASCII actually, but the lazy way that content is loaded).  I recently put in an optimization to not load all the cards in the list -- but when the search happens it wasn't always firing the correct event to fetch more data.

Fix in the next release.

**Comment by derornos** [comment]
thanks! : )
