### ISSUE TITLE
[Questions] How does the 'Burn After Reading' card work in the app?

### ISSUE THREAD

**Issue by derornos** [zzorba/ArkhamCards#419]
Burn After Reading
https://arkhamdb.com/card/08076

How does the 'Burn After Reading' card work in the app?
(2022. 08. taboo)

Signum Crucis (LV 2, XP 0)
https://arkhamdb.com/card/07197

Drawing Thin (LV 0, XP 3)
https://arkhamdb.com/card/05159

As the target of the 'Burn After Reading' card, if I choose the 'Signum Crucis' card or if I choose the 'Drawing Thin' card,
I wonder how the app handles this. (Especially when filling the empty space with cards)

(In the current version, the 'Burn After Reading' card doesn't seem to be able to select a target.)

**Comment by zzorba** [comment]
Working on this issue now -- going to support it first for non-arkhamDB decks, but I've submitted a patch for ArkhamDB to integrate (though who knows if it will ever get merged)

**Comment by derornos** [comment]
Thanks for passing on that news : )
