### ISSUE TITLE
[Bug?] No translation applied: Anton Pavel (zsti_00004)

### ISSUE THREAD

**Issue by derornos** [zzorba/ArkhamCards#429]
en.
https://github.com/zzorba/arkham-cards-data/blob/master/cards/zsti.json#L88

ko.
https://github.com/zzorba/arkham-cards-data/blob/master/i18n/ko/cards/zsti.json#L42

![image](https://user-images.githubusercontent.com/15874357/200204432-9286c3fe-793c-442b-bbf2-12a0a8419025.png)

Do I need to write it to the [ko.po](https://github.com/zzorba/ArkhamCards/blob/master/assets/i18n/ko.po) file?

**Comment by zzorba** [comment]
Thanks, I forgot that this needs to live in the ArkhamCards repo.  Just pushed a new extraction for these three strings.

**Comment by derornos** [comment]
thanks : )
