### ISSUE TITLE
[Bug][i18n][es] "Lead" polysemy

### ISSUE THREAD

**Issue by fafranco82** [zzorba/ArkhamCards#438]
There is a conflict with Spanish translation with the word "Lead". This word is used in basic campaign setup as a label for an icon used to mark who is the lead investigator. So "Lead" was translated to "Jefe" in Spanish becaus "Lead investigator" is "Investigador jefe".

But in the recent Scarlet Keys campaign, this word is used as heading of the info about a city in the travel map, with the meaning of a clue... but this same heading in Spanish is seen as "Jefe" (that's is translated to "Boss" in English).

Can this be fixed in a way similar that I can sea "Lead" also as a trait?

**Comment by zzorba** [comment]
Thanks for reporting. I added new context for this string in the app last night (same issue happened in Russian), so the next release will see a separate translation entry for scarlet keys. Already submitted, but in review.

**Comment by zzorba** [comment]
The lead that now exists in the Arkham cards data repository will be used for just the campaign going forward.
