### ISSUE TITLE
Encounter set names

### ISSUE THREAD

**Issue by matteopic** [zzorba/ArkhamCards#450]
The list of encounter set available from the cards filter screen, shows only English names even there is a translation available.
In the preparation screen names are correctly shown.
![sshot](https://user-images.githubusercontent.com/6689726/208296210-1d9a0551-3ec0-42e4-9d80-8a4608525476.jpg)

**Comment by zzorba** [comment]
I think these encounter sets are coming from ArkhamDB -- but I can theoretically source them from my own datastore now that I have my own card server... let me see what I can do to address this on the backend.
