### ISSUE TITLE
Feature Request: Prevent Auto-Lock

### ISSUE THREAD

**Issue by buffaloseven** [zzorba/ArkhamCards#46]
Just wondering if it'd be possible to add an option to prevent auto-lock for either (a) the whole app, or (b) preferable: when drawing mythos tokens. Would be nice so I don't have to keep unlocking my phone while I play. 👍

**Comment by zzorba** [comment]
I will look into this, totally forgot that is a thing.

**Comment by zzorba** [comment]
Okay, this looks pretty easy to do, thanks for pointing it out. My thought is to enable this on the scenario view, chaos bag odds, and chaos bag draw system, but not the other screens (which tend to be more interactive)? 

What do you think?

**Comment by buffaloseven** [comment]
Well, personally I'd probably only use it on the chaos bag draw system; if I used it more often I'd probably use it on the odds as well. When I'm using it, once the scenario is set up and going, I don't really spend much time on the scenario screen, so I'm not 100% sure what the value is there, but I'm sure there's a use case I can't think of. :-)

And I assume the whole thing will be enabled/disabled by a preference toggle? I've seen some apps also throw a secondary toggle in for only doing it when the phone is plugged in, which could be helpful for some as well.

**Comment by zzorba** [comment]
This is now released, please let me know if you have any other suggestions.
