### ISSUE TITLE
[Feature?] Missing tokens that get added to chaos bag mid-scenario

### ISSUE THREAD

**Issue by profwacko** [zzorba/ArkhamCards#466]
Found in the Path to Carcosa Campaign:

Act 2a in Scenario I (Curtain Call) of The Path To Carcosa campaign adds various tokens to the chaos bag. The app currently does not support manual editing of the chaos bag, and it also does not have a UI for adding these tokens mid-scenario. 

Currently, it is not ideal to use the "draw from bag" feature for this campaign because of this.

**Comment by zzorba** [comment]
Anytime there is a mid scenario change to campaign log or chaos bag like this, there is an option to edit the chaos bag. You can use the undo function to wind back to this point.

**Comment by profwacko** [comment]
Completely missed this button while playing! Will close this issue.

![image](https://user-images.githubusercontent.com/4827688/230638010-5276c637-d7a9-409c-a907-fa861584955d.png)
