### ISSUE TITLE
[Bug] Dark Matter - ADJUST MOMORIES button

### ISSUE THREAD

**Issue by derornos** [zzorba/ArkhamCards#469]
Hello, @zzorba 

I share a bug I encountered while playing the DARK MATTER campaign.

---

１. UI issues where users can't immediately see the resulting value of a change.

At first, I thought that when I hit the ADJUST MOMORIES button, it would load the current value, so to reflect the next +1 from the current +1, I typed in +2 and hit save and saw that the result was +3. (I was expecting +2.)
It was also tiring to have to go back to the CAMPAIGN LOG or the campaign's main screen to see how the values were reflected.

I don't think I would have been confused if the UI looked like this:

[Button: Adjust “Memories”]
```
Rorand Banks +1
Wendy Adans 0
```

[Scenario Logs]
```
Add or remove “Memories”:
Rorand Banks    +1 (3 -> 4)
```

---

２.  Issue with values displayed immediately after pressing the ADJUST MOMORIES button.

When I pressed the ADJUST MOMORIES button, I had a problem with the values displayed. I wanted to adjust from 0 by pressing the + or - buttons, but I was getting completely wrong values, like a -5 value.

---

Thanks for your hard work : )

**Comment by derornos** [comment]
https://user-images.githubusercontent.com/15874357/231608822-1f3b76fa-a4e2-4ced-90ae-78ac48a3d521.mp4

**Comment by zzorba** [comment]
Thanks for detailed report.

Will get to the bottom of this next week, and update when I have a fix pending

**Comment by derornos** [comment]
https://github.com/derornos/ArkhamCards/commit/c049667b9a3a59733220d3374fa3d8b8333e9647

solved.
thanks : )
