### ISSUE TITLE
[Question/bug?] "Class Choice" string in View/Create deck modals appears to be hardcoded in english

### ISSUE THREAD

**Issue by javnik36** [zzorba/ArkhamCards#476]
Hi Daniel,

when I played tsk recently, one of players chose Charlie Kane deck. I have noticed that "Class Choice" (View/Create Deck modals, screenshots below) string is not translated into pl, but I seem not to be able to find this string in translation files. After some digging it looks like it is hardcoded in english, as it appears that way in any language I tried (other characters with "choosing class" do not exhibit that issue, but they only have 1 class to choose - e.g. Gloria Goldberg/Tony Morgan/Many Thompson).

Could you please take a look at this? Super minor issue, but I can't unsee this now xD

<img src="https://user-images.githubusercontent.com/8407785/236424597-138c693f-70f6-4092-ab1a-eedea5a9d674.PNG" width="300"> <img src="https://user-images.githubusercontent.com/8407785/236424629-0832e137-632e-4cdd-aed0-8c16a1b1c85b.PNG" width="300">

**Comment by zzorba** [comment]
Okay, this string is now in the .po file and can be translated.
