### ISSUE TITLE
XP level quick filter directly from the deck list

### ISSUE THREAD

**Issue by akaan** [zzorba/ArkhamCards#49]
When editing a deck I'm either building a level 0 deck or upgrading a deck after a scenario so I often open the filter menu, select "0" or "1-5" as XP filter then apply. That's 3 clicks I do a regular basis.

It would be nice to have a way to filter "0 XP" or "1-5 XP" directly from the deck list instead of having to go through the filter dialog.

**Comment by akaan** [comment]
Great ! 👍

**Comment by zzorba** [comment]
This has been released on both platforms now, thanks for the suggestions!
