### ISSUE TITLE
[Bug] Add card counter stays the same in details view

### ISSUE THREAD

**Issue by Stexinator** [zzorba/ArkhamCards#513]
When you are building a deck and click on a card to get the details view you got an add card widget in the lower right corner. When you add a card and swipe left or right it does not show how many of the card are present in the deck but always the amount of the last card added.

E.g. you add 2x Lucky! and swipe right to see Last Chance, which is not present in the deck, and you see still x2. Due to this you cannot add another card. 

Exiting and entering the details view resets the counter to the card you are opening

**Comment by zzorba** [comment]
That's a recent regression, thanks for reporting.

I'll figure out what's come wrong and push an update.

**Comment by zzorba** [comment]
This should be fixed on both platforms now.
