### ISSUE TITLE
[Bug] "Unspeakable Oath" weakness should show subname

### ISSUE THREAD

**Issue by ombre5733** [zzorba/ArkhamCards#515]
The basic weaknesses Unspeakable Oath have a subname field in the json data, which is not visible.

When a new campaign is set up and the basic weaknesses are selected by the app, it shows only the name of the weakness.
I do not know, if this is only an issue in the German version since the name of the weakness is so long or if the app does not append '(' + subname + ')'. 

Unfortunately, one cannot know the name of the chosen weakness this way.

![Screenshot_ArkhamCards](https://github.com/zzorba/ArkhamCards/assets/4263348/35bc667a-7968-49b1-b821-94b976b62b49)

Note that arkhamdb shows the name as it appears on the card with the subname appended in parenthesis, e.g. [this card](https://arkhamdb.com/card/52013)

**Comment by zzorba** [comment]
Good catch.

As a workaround, you can go to the investigator list on the main campaign screen after this and it should show up (and be tappable) under your investigator

**Comment by zzorba** [comment]
But I'll fix this in the next app version

**Comment by ombre5733** [comment]
Thanks for the workaround. Didn't think about this.

**Comment by zzorba** [comment]
New version should be up on android now that fixes this

**Comment by ombre5733** [comment]
Works fine. Thanks for the quick fix!
