### ISSUE TITLE
Marie deckbuilding options broken 

### ISSUE THREAD

**Issue by stefanesterer** [zzorba/ArkhamCards#543]
Hi!

It seems that there is something weird going on with deckbuilding restrictions for Marie in the current android beta of the arkham cards app. I could not reproduce this on another android phone with the non-beta version.

According to the investigator card (https://arkhamdb.com/card/05006) Marie can't take e.g. Rogue weapons. And survivor card level > 0. But in the app I can add these cards to marie. 

![signal-2023-12-10-092637_002](https://github.com/zzorba/ArkhamCards/assets/1726277/dcd9d5d0-2d9c-46ae-b960-0a39327cfbfd)

A quick check with Lily showed that this behavior is not something every investigator is affected. Lilys deckbuilding for example seems to work just fine.

I've also included the diagnostic data if this helps.

[DiagnosticData-2023-12-10.json](https://github.com/zzorba/ArkhamCards/files/13627039/DiagnosticData-2023-12-10.json)

I'll try to have a look myself if I find the time, any pointers to where the problem lies would be great...

thx for all your work!

**Comment by zzorba** [comment]
Thanks for letting me know, found the bug, will submit a fix today to address it.

**Comment by stefanesterer** [comment]
Verified that the bug has vanished after installing the new version on my android phone.
Much appreciated!
