### ISSUE TITLE
Issue Fix Request: App stalls on iOS device after v4.30

### ISSUE THREAD

**Issue by Mad-Max-13** [zzorba/ArkhamCards#554]
Hi!

After updating the app to v4.3.0, app indefinitely stalls on the splash screen.

Device: iPad Air2, 16GB, iOS 13.5.1

Thanks! ;)

Mad Max

**Comment by zzorba** [comment]
I'll take a look, luckily this is a device I have (but don't use often)

**Comment by zzorba** [comment]
So I have an iPad Air 2 but I'm on IOS 15.3, and I'm not seeing this.  There is a slightly newer app store version (4.3.1) that I posted on Friday, could you try that out? Along with the usual debugging stuff of restarting the iPad and making sure the disk isn't completely full?

If that still doesn't work, could you send me an email at arkhamcards@gmail.com and we can discuss further.
