### ISSUE TITLE
[BUG] a resolute version of Hank deck.

### ISSUE THREAD

**Issue by derornos** [zzorba/ArkhamCards#563]
I was able to create a resolute version of Hank deck in the app.

https://github.com/zzorba/ArkhamCards/assets/15874357/4ce943ae-38e5-4843-9002-3f89902aac78

**Comment by zzorba** [comment]
Thanks for reporting, a duplicate hank snuck in.  If you sync cards he should be gone (but delete the deck first, or it might cause issues).

**Comment by derornos** [comment]
thanks a lot!
: )
