### ISSUE TITLE
Scenario FAQ / Interlude FAQ

### ISSUE THREAD

**Issue by derornos** [zzorba/ArkhamCards#578]
1. link is not working. [example](https://github.com/zzorba/arkham-cards-data/blob/master/errata/ko/errata.json#L253)
Is there anything else I should consider when editing that `ko/errata.json` file?

2. Interlude FAQ issue: [rttcu prologue](https://github.com/zzorba/arkham-cards-data/blob/master/errata/ko/errata.json#L454)
- This creates two FAQ buttons with the same content: Interlude FAQ, Scenario FAQ (ko only)
- I had intended for it to only appear in the `return_to_disappearance_at_the_twilight_estate` interlude, but it appears in the `disappearance_at_the_twilight_estate` interlude as well. Is there any way to fix this? (However, if I change this scenario_code value to `return_to_disappearance_at_the_twilight_estate`, it will not activate any buttons at all.)

**Comment by zzorba** [comment]
I'll fix links working in Q&A, that was previously just not hooked up.  I'll correct that.

As for the `disappearance_at_the_twilight_estate` when building it I made the mistake of not renaming it as a `return` scenario, so it shares the scenarioId with the original.

Let me see about adding a cycle_code to that FAQ entry to account for this.

**Comment by derornos** [comment]
thanks a lot : )
