### ISSUE TITLE
[Bug][i18n][de] Missing Statement in dwl translation

### ISSUE THREAD

**Issue by PEngels** [zzorba/ArkhamCards#592]
There is a bug in the german translation of extracurricalar activities, Dunwhich campaign. 

msgid "Each investigator earns experience equal to the Victory X value of each card in the victory display. **Each investigator earns 1 experience as they reflects on the night’s events.**"
msgstr "Jeder Ermittler verdient Erfahrungspunkte in Höhe des Sieg-X-Wertes aller Karten im Siegpunktestapel."

Here, the additional XP is missing. The english version is correct, though.

**Comment by zzorba** [comment]
Thank you for the fix. I will push a release out sometime next week with this.
