### ISSUE TITLE
[Bug] Probabilistic issue with the results of Draw Random Weakness

### ISSUE THREAD

**Issue by Ruikoto** [zzorba/ArkhamCards#594]
## Problem

When I draw a random weakness (e.g., at the start of a scenario), the probabilities of drawing different random weaknesses are not the same. After hundreds of draws, I found that the probability of drawing a weakness that I have two copies of in my collection is twice as high as drawing a weakness that I only have one copy of.

I personally speculate that this issue is due to a problem with the mechanism to avoid overlap when drawing weaknesses. This results in players being more likely to draw weaknesses from the Core set that has two copies. My friends and I noticed this issue after repeatedly drawing the same weaknesses over several campaigns. This problem is especially severe when players have fewer campaign expansions, making it more likely to draw those weaknesses with two copies from the Core set.

## Solution

I think the logic for drawing random weaknesses can be changed to something like this:

1. Draw each weakness with equal probability.
2. Check for overlap.
3. If there is no overlap, return the result; otherwise, repeat step 1.

**Comment by Ruikoto** [comment]
Although this drawing method seems to simulate shuffling all the weakness cards together and then drawing one in real life, I believe that repeatedly drawing those few weaknesses from the Core Set is not what players expect. I hope you can consider modifying this mechanism. I really love the Arkham Cards app, which has provided me with a lot of convenience for my Arkham journeys. Thanks to the developers!

**Comment by zzorba** [comment]
So I think the design intent is for those weaknesses that there are two of.go appear more frequently. The first several campaigns had some 2x weakness cards, it's only the most recent ones that have switched to all singletons.

I agree on the perception of always receiving the same weaknesses, but I think this is how it was designed and I try to stick to rules as written.

Ive considered adding some weakness variant draws (draw 3, discard one, randomize among 2), or similar, but just haven't had time to build the UI for that.

**Comment by Ruikoto** [comment]
I understand, thank you for your explanation.
