### ISSUE TITLE
Markdown headers in deck notes render cropped

### ISSUE THREAD

**Issue by mattijv** [zzorba/ArkhamCards#613]
> Thank you for all your work on this amazing app!

## System
- iOS 17.6.1
- AkrhamCards 4.7.1
- Font Size: default

## Steps to reproduce
1. Open the deck note editor and add a Markdown header (e.g. `# foo`).
2. Save and observe the rendered note.

The header is rendered with its top part cropped (the effect is worse the larger the heading is).

![markdown](https://github.com/user-attachments/assets/50b80ef1-8e18-4e4b-a7b4-3fba85614902)

![rendered](https://github.com/user-attachments/assets/124a72ce-566c-43e0-9541-7d00c9a81be4)

**Comment by mattijv** [comment]
The Theme and Font Size settings in the app did not seem to affect the issue.

**Comment by zzorba** [comment]
Fixed this, its in the CardTextComponent section.  Will go out in next release.

**Comment by mattijv** [comment]
Confirming this is fixed. Thank you for the quick fix :pray:
