### ISSUE TITLE
Missed Encounter Icons

### ISSUE THREAD

**Issue by neizerth** [zzorba/ArkhamCards#614]
Currently IcoMoon haven't these encounter icons:

- The Blob That Ate Everything Else
-  migo_incursion_2

**Comment by fspoettel** [comment]
![blbe](https://github.com/user-attachments/assets/a6cbc239-0ad8-4066-862c-d94c0ed9a270)
![blob_that_ate_everything_else](https://github.com/user-attachments/assets/1581b14f-eb3e-43a0-bbe8-0e270f0483ad)
![migo_incursion_2](https://github.com/user-attachments/assets/c8f3c929-02bf-491b-a02b-d8bcbc40d9cb)

@neizerth here you go.

**Comment by neizerth** [comment]
@fspoettel Thank you!

**Comment by neizerth** [comment]
It would be good if these icons will be in IcoMoon project 

If i will have some time, I'll do a PR

**Comment by fspoettel** [comment]
@neizerth Thanks! I think we are missing the encounter sets as part of `arkhamdb-json-data`, once they are there, we will have to  add them here as well.

**Comment by fspoettel** [comment]
looks like the icons are now part of the icomoon project. 🎉

**Comment by neizerth** [comment]
@fspoettel Yep! Thank you! Thats perfect!
