### ISSUE TITLE
In the checklist for easier deckbuilding, add as many checkboxes as you have copies of that card

### ISSUE THREAD

**Issue by eike** [zzorba/ArkhamCards#622]
Often, when using the checklist, I am reassembling a deck that has some cards stolen for use in other decks. The deck is therefore still shuffled from the last scenario, and it is not guaranteed that all copies of the same card will appear right after each other. Therefore, it would be nice if one could check individual copies of cards, by providing as many checkboxes as there are copies of that card in the deck. (Tapping a checkbox could mark all the boxes to the left of it automatically, as with Customizable cards, so there are no extra taps needed if the cards are sorted.)

(Please let me know if there is a better place for feature requests, or if feature requests are wholly unwanted.)

**Comment by zzorba** [comment]
Not a bad idea, I think I have a control that works something like this, will see what I can do.

**Comment by zzorba** [comment]
Okay, I've built this, will add it to the next release.

**Comment by eike** [comment]
This is great, and so quick! Thanks!
