### ISSUE TITLE
Dream-Eaters guided campaign : Epilogue when playing as 4-part

### ISSUE THREAD

**Issue by akaan** [zzorba/ArkhamCards#90]
Hi,

When playing the Dream-Eaters as a four-part campaign (either A or B), there should be no Epilogue after the last scenario.
Totally not a priority.

Akaan

**Comment by zzorba** [comment]
Turns out I had marked the campaign as skipping `epilogue` when the name of the scenario was actually `tde_epilogue`, fix will go out in the next release.
